namespace ScintillaNET;

/// <summary>
/// <see cref="SciApi.SCNotification.characterSource"/> type for the <see cref="SciApi.SCN_CHARADDED"/> event.
/// </summary>
public enum CharacterSource
{
    /// <summary>
    /// Direct input characters, including characters generated by calling keyboard commands like <see cref="SciApi.SCI_NEWLINE"/>.
    /// </summary>
    DirectInput = SciApi.SC_CHARACTERSOURCE_DIRECT_INPUT,

    /// <summary>
    /// Tentative input characters. They are used by IME (inline mode, see <see cref="SciApi.SCI_SETIMEINTERACTION"/>) to composite final string, normally different from final composited string (which is the string that has been truly added into current document), and may be withdrawn when the user cancels typing (e.g. by pressing Esc key). Some system (at least Cocoa) also use tentative input for non-IME features like using dead key to composite diacritical marks (grave accent, etc.). These characters are not added to macro recording. Most applications can simply ignore the notification when this value is set.
    /// </summary>
    TentativeInput = SciApi.SC_CHARACTERSOURCE_TENTATIVE_INPUT,

    /// <summary>
    /// IME (either inline or windowed mode) full composited string. Modern IME is able to composite English word or sentence, when this value is set, current character may not a Chinese, Japanese or Korean character. Currently, this is only set on Windows.
    /// </summary>
    ImeResult = SciApi.SC_CHARACTERSOURCE_IME_RESULT,
}
